[workspace]
members = ["crates/core", "crates/rpc", "crates/cli"]
exclude = ["examples"]
resolver = "2"

[workspace.dependencies]
async-std = "1.12.0"
eyre = "0.6.8"
serde = "1.0.156"
serde_with = "2.3.3"
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs", rev = "082f5564cf77a128139d8c2acc4f27ba670780ab" }
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
