[package]
name = "beerus"
version = "0.1.0"
edition = "2021"

[dependencies]
helios = { git = "https://github.com/a16z/helios" }
ethers = { git = "https://github.com/gakonst/ethers-rs" }
eyre = "0.6.8"
tokio = { version = "1.21.2", features = ["full"] }