name: ci
on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # rust action deps
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: install hurl
        run: cargo install --version 4.1.0 hurl

      - name: build beerus
        run: cargo build -p beerus-cli --release

      - name: start beerus RPC on MAINNET
        env:
          BEERUS_VERSION: "ci"
          NETWORK: "mainnet"
          ETH_EXECUTION_RPC: ${{ secrets.ETH_EXECUTION_RPC_MAINNET }}
          STARKNET_RPC: ${{ secrets.STARKNET_RPC_MAINNET }}
        run: ./target/release/beerus &
      - name: run integration test on MAINNET
        run: bash ./scripts/integration-test.sh mainnet

      - name: stop RPC
        run: kill $(lsof -t -i:3030)

      - name: start beerus RPC on TESTNET(goerli)
        env:
          BEERUS_VERSION: "ci"
          NETWORK: "goerli"
          ETH_EXECUTION_RPC: ${{ secrets.ETH_EXECUTION_RPC_GOERLI }}
          STARKNET_RPC: ${{ secrets.STARKNET_RPC_GOERLI }}
        run: ./target/release/beerus &

      - name: run integration test TESTNET(goerli)
        run: bash ./scripts/integration-test.sh goerli
